name: pyinstaller-build
on: push
jobs:
  pyinstaller-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: install dependencies
        run: |
          python -m pip install poetry
          python -m poetry --directory gui install --with dev

      - name: Create Executable
        run: |
          cd gui
          python scripts/build.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7.0.0
        with:
          name: pyquantsim-${{ matrix.os }}
          path: gui/dist/app/
